language: node_js
cache:
  directories:
    - ${HOME}/node_modules
git:
  depth: 1
notifications:
  email: false
jobs:
  include:
    - stage: commit
      node_js: lts/*
      script: npm run test
stages:
  - name: warmup
  - name: commit
  - name: test
